In [1]:
# Introduce imports which we need
import pandas as pd
import numpy as np

In [2]:
# Load data exported from Wharton

df_returns= pd.read_csv('/Users/sebastiansydow/8_FM/99_coke_returns_test.csv')

In [3]:
df_returns

     PERMNO      date        COMNAM     CUSIP       RET
0     11308  20010131  COCA COLA CO  19121610 -0.048205
1     11308  20010228  COCA COLA CO  19121610 -0.085690
2     11308  20010330  COCA COLA CO  19121610 -0.145012
3     11308  20010430  COCA COLA CO  19121610  0.022808
4     11308  20010531  COCA COLA CO  19121610  0.026196
..      ...       ...           ...       ...       ...
235   11308  20200831  COCA COLA CO  19121610  0.048476
236   11308  20200930  COCA COLA CO  19121610  0.005047
237   11308  20201030  COCA COLA CO  19121610 -0.026534
238   11308  20201130  COCA COLA CO  19121610  0.082189
239   11308  20201231  COCA COLA CO  19121610  0.062791

[240 rows x 5 columns]

In [11]:
a = df_returns.iloc[0:12, :]

In [5]:
# Create Columns for Event and Dummy 
a.loc[0:, 'Event'] = np.nan
a.loc[0:, 'Dummy'] = np.nan

# Indicate the time of investment
a.loc[6, 'Dummy'] = 1

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:845: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [6]:
a

    PERMNO      date        COMNAM     CUSIP       RET  Event  Dummy
0    11308  20010131  COCA COLA CO  19121610 -0.048205    NaN    NaN
1    11308  20010228  COCA COLA CO  19121610 -0.085690    NaN    NaN
2    11308  20010330  COCA COLA CO  19121610 -0.145012    NaN    NaN
3    11308  20010430  COCA COLA CO  19121610  0.022808    NaN    NaN
4    11308  20010531  COCA COLA CO  19121610  0.026196    NaN    NaN
5    11308  20010629  COCA COLA CO  19121610 -0.046835    NaN    NaN
6    11308  20010731  COCA COLA CO  19121610 -0.008889    NaN    1.0
7    11308  20010831  COCA COLA CO  19121610  0.091256    NaN    NaN
8    11308  20010928  COCA COLA CO  19121610 -0.033696    NaN    NaN
9    11308  20011031  COCA COLA CO  19121610  0.021985    NaN    NaN
10   11308  20011130  COCA COLA CO  19121610 -0.015455    NaN    NaN
11   11308  20011231  COCA COLA CO  19121610  0.004046    NaN    NaN

In [7]:
def returns(df):
    length = len(df)
    i = 0
    while i < length:
        if df.loc[i, 'Dummy'] == 1:
            # Add Dummy Variables
            df.loc[i+1,'Dummy'] = 1
            df.loc[i+2,'Dummy'] = 1
            df.loc[i-1,'Dummy'] = 0
            df.loc[i-2,'Dummy'] = 0
            df.loc[i-3,'Dummy'] = 0
            # Add Eventtime
            df.loc[i,'Event'] = 0
            df.loc[i+1,'Event'] = 1
            df.loc[i+2,'Event'] = 2
            df.loc[i-1,'Event'] = -1
            df.loc[i-2,'Event'] = -2
            df.loc[i-3,'Event'] = -3
            i += 3
        else:
            i += 1
        
    df = df.dropna()
    return df

In [8]:
b = returns(a)

/opt/anaconda3/lib/python3.8/site-packages/pandas/core/indexing.py:966: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [9]:
b

   PERMNO      date        COMNAM     CUSIP       RET  Event  Dummy
3   11308  20010430  COCA COLA CO  19121610  0.022808   -3.0    0.0
4   11308  20010531  COCA COLA CO  19121610  0.026196   -2.0    0.0
5   11308  20010629  COCA COLA CO  19121610 -0.046835   -1.0    0.0
6   11308  20010731  COCA COLA CO  19121610 -0.008889    0.0    1.0
7   11308  20010831  COCA COLA CO  19121610  0.091256    1.0    1.0
8   11308  20010928  COCA COLA CO  19121610 -0.033696    2.0    1.0